<?php

namespace AppBundle\Repository;

/**
 * CandidatureNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatureNoteRepository extends \Doctrine\ORM\EntityRepository
{
}
