<?php

namespace AppBundle\Repository;

/**
 * ClientVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
