<?php

namespace AppBundle\Repository;

/**
 * VoteCandidatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteCandidatureRepository extends \Doctrine\ORM\EntityRepository
{
}
